#! /bin/bash
#
#this script take the two automata_file.txt generated by main_script.py and create two different transducers
#
# no input line parameters are taken

fstcompile --isymbols=lexicon_lower.txt --osymbols=lexicon_lower.txt automata_lower.txt > automata_lower.fst
fstcompile --isymbols=lexicon_upper.txt --osymbols=lexicon_upper.txt automata_upper.txt > automata_upper.fst

