#! /bin/bash
#
#this script take the three automata_file.txt generated by ind_feat_script.py and create three different transducers
#the three transducers are sorted and composed together in order to create a unique transducer
#
# no input line parameters are taken

fstcompile --isymbols=lexicon_lemmatization.txt --osymbols=lexicon_lemmatization.txt automata_1.txt > automata_1.fst
fstcompile --isymbols=lexicon_lemmatization.txt --osymbols=lexicon_lemmatization.txt automata_2.txt > automata_2.fst
fstcompile --isymbols=lexicon_lemmatization.txt --osymbols=lexicon_lemmatization.txt automata_3.txt > automata_3.fst

fstarcsort automata_1.fst > automata_1_sort.fst
fstarcsort automata_2.fst > automata_2_sort.fst
fstarcsort automata_3.fst > automata_3_sort.fst

fstcompose automata_1_sort.fst automata_2_sort.fst | fstcompose - automata_3_sort.fst > automata_complete.fst
