#! /bin/bash

#create the transducers given the automata file .txt generated by main.py script

#no input line parameters required

fstcompile --isymbols=lexicon_word.txt --osymbols=lexicon_word.txt automata_1.txt > automata_1.fst
fstcompile --isymbols=lexicon_lemma.txt --osymbols=lexicon_lemma.txt automata_2.txt > automata_2.fst
fstcompile --isymbols=lexicon_pos.txt --osymbols=lexicon_pos.txt automata_3.txt > automata_3.fst

fstarcsort automata_1.fst > automata_1_sort.fst
fstarcsort automata_2.fst > automata_2_sort.fst
fstarcsort automata_3.fst > automata_3_sort.fst


